# Generated by Django 4.2.1 on 2023-06-05 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parfume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Parfume',
            new_name='parfume',
        ),
    ]
